### ISSUE TITLE
Allow kop matches to display only latest matches

### ISSUE THREAD

**Issue by Fvdbrant** [damoonrashidi/ladder#10]
As title says, add the possibility to only display the latest 5, 10, 20 matches or (if possible) the last matches on the current day. 

/Frederik

**Comment by chaaya** [comment]
Is this repo actively maintained? It has been 5 days since @Fvdbrant opened this issue and still no answer? Please label it "under investigation" or something so we know what to expect from the next release.

**Comment by damoonrashidi** [comment]
Fixed and released in 2.3.2
