### ISSUE TITLE
Store authentication response in shared_preferences

### ISSUE THREAD

**Issue by damoonrashidi** [damoonrashidi/ladder#4]
In the `home.widget.dart` file. A request to the firebase API is made to authenticate the user. The request will return a user object which has a `displayName` property. That property needs to be stored in shared_preferences.

the key to use when storing the displayName property in shared preferences should be `current_user`

[More on shared_preferences](https://pub.dartlang.org/packages/shared_preferences).

**Comment by kondanta** [comment]
If it's ok I'd like to take this

**Comment by damoonrashidi** [comment]
That would be great @kondanta! Thanks for helping

**Comment by damoonrashidi** [comment]
Ye that was a mistake putting it in at all, i should even clear the git commits with the API key. But since it's still super early in development and the key doesn't really matter you can still use the same one that was in the previous commits, that should work
